node {
 
  dir('aws-demo') {
 
    stage('Init') {
      echo 'Terraform init'
      sh 'pwd'
      sh 'ls -la'
      sh 'terraform init'
    }

    stage('Plan') {
      echo 'Terraform plan'
    
    }
  }
}

