node {

  stage('Scm') {
    checkout scm
  }

  stage('Init env variables') {
    env.AWS_ACCESS_KEY_ID = ''
    env.AWS_SECRET_ACCESS_KEY = ''
    env.AWS_DEFAULT_REGION = 'us-east-2'
  }
 
  dir('aws-demo') {

 
    stage('Init') {
      echo 'Terraform init'
      sh 'terraform init'
    }

    stage('Plan') {
      echo 'Terraform plan'
      sh 'terraform plan'
    }

    stage('Approval') {
      def userInput = input(id: 'confirm', message: 'Apply terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ] )
      if ( userInput ) {
         echo 'true'
      } else {
        echo 'false'
      }
    }
  }
}

