node {

  def userInput = false
  stage('Scm') {
    checkout scm
  }

  stage('Init env variables') {
    withCredentials([usernamePassword(credentialsId: 'antonio.mc_keyid', passwordVariable: 'access_key', usernameVariable: 'key_id')]) {
   
      env.AWS_ACCESS_KEY_ID = "${key_id}"
      env.AWS_SECRET_ACCESS_KEY = "${access_key}"
      env.AWS_DEFAULT_REGION = 'us-east-2'
    }
  }
 
  dir('aws-demo') {

 
    stage('Init') {
      echo 'Terraform init'
      sh 'terraform init'
    }

    stage('Plan') {
      echo 'Terraform plan'
      sh 'terraform plan'
    }

    stage('Choose action') {
      actionUserInput = input(id: 'action', message: 'Choose action', parameters: [ [$class: 'ChoiceParameterDefinition', choices: "Apply\nDestroy", description: 'Choose action', name: 'Action'] ] )

      echo "Action selected: ${actionUserInput}"	

    }

    stage('Approval') {
      userInput = input(id: 'confirm', message: 'Apply terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ] )
         
    }

    stage('Apply') {
      
      if ( userInput ) {
        
        sh 'terraform apply -auto-approve -input=false' 
      } else {
        
        sh 'terraform destroy -auto-approve' 
      }
    }
  }
}

